### ISSUE TITLE
Crash after several Invoke calls on VBScriptEngine

### ISSUE THREAD

**Issue by skacurt** [microsoft/ClearScript#174]
Hi,

If you run the program below several times, you'll probably see that ~90% of processes crash silently on 6th `engine.Invoke` call, the rest throws an `AccessViolationException`  on 7th only if the previous (6th) was a `CStr` invocation, it **never** reach the 8th. 

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.ClearScript.Windows;

public class Program
{
    public static void Main()
    {
        using (var engine = new VBScriptEngine())
        {
            var random = new Random();
            var functions = new List<string>
            {
                "CDate", "CStr", "CDbl", "CSng", "CCur",
                "CLng", "CInt", "CByte", "CBool"
            };

            foreach (var (method, index) in functions.
                OrderBy(f => random.NextDouble()).Select((m, i) => (m, i + 1)))
            {
                Console.Write($"Call {index}: {method} is being invoked. ");
                engine.Invoke(method, "1");
                Console.WriteLine("Done.");
            }
        }
    }
}
```

2 typical outputs:

Silent crash:
```
>Program.exe
Call 1: CDate is being invoked. Done.
Call 2: CStr is being invoked. Done.
Call 3: CInt is being invoked. Done.
Call 4: CLng is being invoked. Done.
Call 5: CCur is being invoked. Done.
Call 6: CDbl is being invoked.
```

Crash with exception:
```
>Program.exe
Call 1: CInt is being invoked. Done.
Call 2: CByte is being invoked. Done.
Call 3: CLng is being invoked. Done.
Call 4: CDbl is being invoked. Done.
Call 5: CDate is being invoked. Done.
Call 6: CStr is being invoked. Done.
Call 7: CSng is being invoked.
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Microsoft.ClearScript.Util.COM.IDispatchEx.InvokeEx(Int32 dispid, Int32 lcid, DispatchFlags flags, DISPPARAMS& args, IntPtr pVarResult, EXCEPINFO& excepInfo, IServiceProvider svpCaller)
   at Microsoft.ClearScript.Util.COM.DispatchExHelpers.InvokeMethod(IDispatchEx dispatchEx, String name, Boolean ignoreCase, Object[] args)
   at Microsoft.ClearScript.Windows.WindowsScriptItem.<>c__DisplayClass20_0.<InvokeMethod>b__0()
   at Microsoft.ClearScript.Windows.WindowsScriptEngine.<>c__DisplayClass57_0`1.<ScriptInvoke>b__0()
   at Microsoft.ClearScript.ScriptEngine.ScriptInvokeInternal[T](Func`1 func)
   at Microsoft.ClearScript.ScriptEngine.ScriptInvoke[T](Func`1 func)
   at Microsoft.ClearScript.Windows.WindowsScriptEngine.ScriptInvoke[T](Func`1 func)
   at Microsoft.ClearScript.Windows.WindowsScriptItem.InvokeMethod(String name, Object[] args)
   at Microsoft.ClearScript.ScriptEngine.Invoke(String funcName, Object[] args)
   at Program.Main() in C:\<path>\Program.cs:line 23
```

**Comment by ClearScriptLib** [comment]
Hi @skacurt,

Unfortunately these functions don't seem to support external invocation; that is, the only way to call them safely is from script code.

One thing you could do is invoke them from user-defined wrappers:

``` C#
var wrappers = functions.Select(f => $"function my{f}(x):my{f}={f}(x):end function");
engine.Execute(string.Join(":", wrappers));
```

And then:

``` C#
engine.Invoke("my" + method, "1");
```

We've tested this with up to 100,000 iterations and encountered no issues.

Good luck!

**Comment by skacurt** [comment]
> Unfortunately these functions don't seem to support external invocation; that is, the only way to call them safely is from script code.

Then I can live with that. Thanks!
