### ISSUE TITLE
Running net core5 app inside Docker container fails with error Invalid class string (0x800401F3 (CO_E_CLASSSTRING))

### ISSUE THREAD

**Issue by sven634231** [microsoft/ClearScript#297]
While it is running fine in IIS it shows an error if executed inside a docker windows container.

line: var scriptControl = new Microsoft.ClearScript.Windows.Core.VBScriptEngine(Microsoft.ClearScript.Windows.WindowsScriptEngineFlags.EnableDebugging, Microsoft.ClearScript.Windows.Core.NullSyncInvoker.Instance);

System.Runtime.InteropServices.COMException: 'Invalid class string (0x800401F3 (CO_E_CLASSSTRING))'

at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
at Microsoft.ClearScript.Util.COM.HResult.Check(Int32 result)
at Microsoft.ClearScript.Util.COM.HResult.Check(UInt32 result)
at Microsoft.ClearScript.Util.COM.ActivationHelpers.CLSIDFromProgID(String progID)
at Microsoft.ClearScript.Util.COM.ActivationHelpers.CreateInstance[T](String progID)
at Microsoft.ClearScript.Windows.Core.ActiveScriptWrapper64..ctor(String progID, WindowsScriptEngineFlags flags)
at Microsoft.ClearScript.Windows.Core.ActiveScriptWrapper.Create(String progID, WindowsScriptEngineFlags flags)
at Microsoft.ClearScript.Windows.Core.WindowsScriptEngine.<>c__DisplayClass13_0.<.ctor>b__0()
at Microsoft.ClearScript.ScriptEngine.ScriptInvokeInternal[T](Func1 func) at Microsoft.ClearScript.ScriptEngine.ScriptInvoke[T](Func1 func)
at Microsoft.ClearScript.Windows.Core.WindowsScriptEngine..ctor(String progID, String name, String fileNameExtensions, WindowsScriptEngineFlags flags, ISyncInvoker syncInvoker)
at Microsoft.ClearScript.Windows.Core.VBScriptEngine..ctor(String progID, String name, String fileNameExtensions, WindowsScriptEngineFlags flags, ISyncInvoker syncInvoker)
at Microsoft.ClearScript.Windows.Core.VBScriptEngine..ctor(String name, WindowsScriptEngineFlags flags, ISyncInvoker syncInvoker)
at Microsoft.ClearScript.Windows.Core.VBScriptEngine..ctor(WindowsScriptEngineFlags flags, ISyncInvoker syncInvoker)
at RunnerCoreKube.Controllers.WeatherForecastController.vba() in c:...\ScriptController.cs:line 67
at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()

**Comment by sven634231** [comment]
While javascript is running fine within docker:

var scriptControl = new Microsoft.ClearScript.V8.V8ScriptEngine(Microsoft.ClearScript.V8.V8ScriptEngineFlags.EnableDebugging);            scriptControl.Execute("value_out = 5 + 8");

Also the other way of defining the object

var scriptControlVb = new Microsoft.ClearScript.Windows.VBScriptEngine(); 

shows an error:

System.TypeLoadException: 'Could not load type 'System.Windows.Threading.Dispatcher' from assembly 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.'

   at Microsoft.ClearScript.Windows.DispatcherSyncInvoker..ctor()
   at Microsoft.ClearScript.Windows.WindowsScriptEngine..ctor(String progID, String name, String fileNameExtensions, WindowsScriptEngineFlags flags)
   at Microsoft.ClearScript.Windows.VBScriptEngine..ctor(String progID, String name, String fileNameExtensions, WindowsScriptEngineFlags flags)
   at Microsoft.ClearScript.Windows.VBScriptEngine..ctor(String name, WindowsScriptEngineFlags flags)
   at Microsoft.ClearScript.Windows.VBScriptEngine..ctor(String name)
   at Microsoft.ClearScript.Windows.VBScriptEngine..ctor()
   at RunnerCoreKube.Controllers.WeatherForecastController.vba() in C:\..ScriptController.cs:line 71
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()

 <Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <DockerDefaultTargetOS>Windows</DockerDefaultTargetOS>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ClearScript" Version="7.1.6" />
    <PackageReference Include="Microsoft.ClearScript.Core" Version="7.1.6" />
    <PackageReference Include="Microsoft.ClearScript.V8" Version="7.1.6" />
    <PackageReference Include="Microsoft.ClearScript.V8.Native.win-x64" Version="7.1.6" />
    <PackageReference Include="Microsoft.ClearScript.V8.Native.win-x86" Version="7.1.6" />
    <PackageReference Include="Microsoft.ClearScript.Windows" Version="7.1.6" />
    <PackageReference Include="Microsoft.ClearScript.Windows.Core" Version="7.1.6" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.11.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Kubernetes.Tools.Targets" Version="1.1.0" />
  </ItemGroup>
</Project>
