### ISSUE TITLE
Microsoft.ClearScript.V8.Native.osx-x64 package is no longer compatible with macOS 10.13 

### ISSUE THREAD

**Issue by Taritsyn** [microsoft/ClearScript#333]
Hello!

After updating the Microsoft.ClearScript.V8.Native.osx-x64 package from version 7.1.7 to 7.2.0, an error began to occur on macOS 10.13.6:

```
…
System.TypeLoadException : Cannot load ClearScript V8 library. Load failure information for ClearScriptV8.osx-x64.dylib:
/Users/dron/TestsForUnix/src/TestsForUnix/bin/Debug/net6.0/runtimes/osx-x64/native/ClearScriptV8.osx-x64.dylib: Unable to load shared library '/Users/tester/TestsForUnix/src/TestsForUnix/bin/Debug/net6.0/runtimes/osx-x64/native/ClearScriptV8.osx-x64.dylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(/Users/tester/TestsForUnix/src/TestsForUnix/bin/Debug/net6.0/runtimes/osx-x64/native/ClearScriptV8.osx-x64.dylib, 1): no suitable image found.  Did find:
	/Users/tester/TestsForUnix/src/TestsForUnix/bin/Debug/net6.0/runtimes/osx-x64/native/ClearScriptV8.osx-x64.dylib: cannot load 'ClearScriptV8.osx-x64.dylib' (load command 0x80000034 is unknown)
	/Users/tester/TestsForUnix/src/TestsForUnix/bin/Debug/net6.0/runtimes/osx-x64/native/ClearScriptV8.osx-x64.dylib: cannot load 'ClearScriptV8.osx-x64.dylib' (load command 0x80000034 is unknown)
/Users/tester/TestsForUnix/src/TestsForUnix/bin/Debug/net6.0/ClearScriptV8.osx-x64.dylib: Unable to load shared library '/Users/tester/TestsForUnix/src/TestsForUnix/bin/Debug/net6.0/ClearScriptV8.osx-x64.dylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(/Users/tester/TestsForUnix/src/TestsForUnix/bin/Debug/net6.0/ClearScriptV8.osx-x64.dylib, 1): image not found
/System/ClearScriptV8.osx-x64.dylib: Unable to load shared library '/System/ClearScriptV8.osx-x64.dylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(/System/ClearScriptV8.osx-x64.dylib, 1): image not found
  Stack Trace:
   …
----- Inner Stack Trace -----
   at Microsoft.ClearScript.V8.V8Proxy.LoadNativeLibrary(String baseName, String platform, String architecture, String extension)
   at Microsoft.ClearScript.V8.V8Proxy.LoadNativeAssembly()
   at Microsoft.ClearScript.V8.V8Proxy.OnEntityHolderCreated()
   at Microsoft.ClearScript.V8.SplitProxy.V8EntityHolder..ctor(String name, Func`1 acquireHandle)
   at Microsoft.ClearScript.V8.SplitProxy.V8IsolateProxyImpl..ctor(String name, V8RuntimeConstraints constraints, V8RuntimeFlags flags, Int32 debugPort)
   at Microsoft.ClearScript.V8.V8IsolateProxy.Create(String name, V8RuntimeConstraints constraints, V8RuntimeFlags flags, Int32 debugPort)
   at Microsoft.ClearScript.V8.V8Runtime..ctor(String name, V8RuntimeConstraints constraints, V8RuntimeFlags flags, Int32 debugPort)
   at Microsoft.ClearScript.V8.V8Runtime..ctor(String name, V8RuntimeConstraints constraints, V8RuntimeFlags flags)
   at Microsoft.ClearScript.V8.V8Runtime..ctor(String name, V8RuntimeConstraints constraints)
   at Microsoft.ClearScript.V8.V8ScriptEngine..ctor(V8Runtime runtime, String name, V8RuntimeConstraints constraints, V8ScriptEngineFlags flags, Int32 debugPort)
   at Microsoft.ClearScript.V8.V8ScriptEngine..ctor(String name, V8RuntimeConstraints constraints, V8ScriptEngineFlags flags, Int32 debugPort)
   at Microsoft.ClearScript.V8.V8ScriptEngine..ctor(V8RuntimeConstraints constraints, V8ScriptEngineFlags flags, Int32 debugPort)
   …
```

It is possible that the build was made with some newer dependencies.

**Comment by ClearScriptLib** [comment]
Hi Andrey,

Apple no longer supports macOS 10.13 or 10.14, so it's possible that neither does Xcode. ClearScript 7.2 didn't change anything about how it builds the native macOS libraries.

Oddly, we can find very little mention of this error message ("load command 0x80000034 is unknown"), but it seems relatively recent and not specific to ClearScript.

We'll keep this issue open for now; hopefully some new information will come to light soon.

Thanks!

**Comment by ClearScriptLib** [comment]
Hi Andrey,

The only new information we've been able to find is that `0x80000034` corresponds to a recently added macOS loader command constant –`LC_DYLD_CHAINED_FIXUPS`. Given the stack above, that generally points at a low-level incompatibility between the old macOS version and ClearScript's native V8 shared library.

Unfortunately, we're not aware of a workaround for this issue. It might be possible to build a compatible library on an old macOS version with old development tools, but that's not something we can take on.

Interestingly, this is similar to an issue on Linux, where glibc changes made newer ClearScript builds unusable on older Linux versions. V8 installs its own Linux build tools, however, and we've able to roll those back far enough to build libraries compatible with most in-use Linux versions, at least so far.

If you get a chance, please try ClearScript 7.3; changes to improve [.NET playground](https://microsoft.github.io/ClearScript/2022/06/15/playground-environments.html) deployment affect the crashing code path above. Otherwise, please reopen this issue if you have additional questions or findings on this topic.

As always, thank you!

**Comment by Taritsyn** [comment]
Thanks for information!

I checked the joint work of the JavaScriptEngineSwitcher.V8 and Microsoft.ClearScript.V8.Native.linux-x64 packages in the .NET Fiddle - everything works fine.
