### ISSUE TITLE
Cant Build ClearScript

### ISSUE THREAD

**Issue by jeypevillarubia** [microsoft/ClearScript#414]
Every time I run V8update it stops on Downloading V8 and dependencies I've already tried both Tested and Release but they have the same error.

I wish you could help me T_T

C:\ClearScript> V8Update Release tested
Build mode: Release
V8 revision: Tested (10.5.218.8)
Removing old build directory ...
Creating build directory ...
Downloading Depot Tools ...
Expanding Depot Tools ...
Downloading V8 and dependencies ...
*** THE PREVIOUS STEP FAILED ***

**Comment by ClearScriptLib** [comment]
Hi @jeypevillarubia,

Do you see any `.log` files in `C:\ClearScript\V8\build\v8`?

Thanks!

**Comment by jeypevillarubia** [comment]
I can't see another v8 folder inside the build folder. but there is a log file inside the build folder named config.log and sync.log 

the sync log has error saying
Updating depot_tools...

fatal: unable to access 'https://chromium.googlesource.com/chromium/tools/depot_tools.git/': SSL certificate problem: self signed certificate in certificate chain

**Comment by ClearScriptLib** [comment]
Hi @jeypevillarubia,

We can't reproduce this, but a search revealed the following potential workaround:

1. Run `git config --global http.sslVerify false`.
2. Run the `V8Update` script as before.
3. Run `git config --global --unset http.sslVerify`.

Please let us know if this works for you.

Good luck!

**Comment by jeypevillarubia** [comment]
It still won't work T_T but I got a new error



Updating depot_tools...

v8 (ERROR)
----------------------------------------
[0:00:00] Started.
----------------------------------------
Traceback (most recent call last):
  File "C:\ClearScript\V8\build\DepotTools\metrics.py", line 291, in print_notice_and_exit
    yield
  File "C:\ClearScript\V8\build\DepotTools\gclient.py", line 3468, in <module>
    sys.exit(main(sys.argv[1:]))
  File "C:\ClearScript\V8\build\DepotTools\gclient.py", line 3454, in main
    return dispatcher.execute(OptionParser(), argv)
  File "C:\ClearScript\V8\build\DepotTools\subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "C:\ClearScript\V8\build\DepotTools\gclient.py", line 3005, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "C:\ClearScript\V8\build\DepotTools\gclient.py", line 2011, in RunOnDeps
    work_queue.flush(revision_overrides,
  File "C:\ClearScript\V8\build\DepotTools\gclient_utils.py", line 1013, in flush
    reraise(e[0], e[1], e[2])
  File "C:\ClearScript\V8\build\DepotTools\gclient_utils.py", line 70, in reraise
    raise value
  File "C:\ClearScript\V8\build\DepotTools\gclient_utils.py", line 1090, in run
    self.item.run(*self.args, **self.kwargs)
  File "C:\ClearScript\V8\build\DepotTools\gclient.py", line 1005, in run
    self._got_revision = self._used_scm.RunCommand(command, options, args,
  File "C:\ClearScript\V8\build\DepotTools\gclient_scm.py", line 128, in RunCommand
    return getattr(self, command)(options, args, file_list)
  File "C:\ClearScript\V8\build\DepotTools\gclient_scm.py", line 610, in update
    mirror = self._GetMirror(url, options, revision, revision_ref)
  File "C:\ClearScript\V8\build\DepotTools\gclient_scm.py", line 1060, in _GetMirror
    if not self.cache_dir:
  File "C:\ClearScript\V8\build\DepotTools\gclient_scm.py", line 225, in cache_dir
    return git_cache.Mirror.GetCachePath()
  File "C:\ClearScript\V8\build\DepotTools\git_cache.py", line 193, in GetCachePath
    cachepath = subprocess.check_output(
  File "C:\ClearScript\V8\build\DepotTools\.cipd_bin\3.8\bin\Lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\ClearScript\V8\build\DepotTools\.cipd_bin\3.8\bin\Lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\ClearScript\V8\build\DepotTools\.cipd_bin\3.8\bin\Lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\ClearScript\V8\build\DepotTools\.cipd_bin\3.8\bin\Lib\subprocess.py", line 1334, in _execute_child
    _winapi.CloseHandle(ht)
OSError: [WinError 6] The handle is invalid
Exception ignored in: <function Popen.__del__ at 0x000001F1F70A7550>
Traceback (most recent call last):
  File "C:\ClearScript\V8\build\DepotTools\.cipd_bin\3.8\bin\Lib\subprocess.py", line 949, in __del__
    self._internal_poll(_deadstate=_maxsize)
  File "C:\ClearScript\V8\build\DepotTools\.cipd_bin\3.8\bin\Lib\subprocess.py", line 1348, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
OSError: [WinError 6] The handle is invalid
Exception ignored in: <function Handle.Close at 0x000001F1F709B820>
Traceback (most recent call last):
  File "C:\ClearScript\V8\build\DepotTools\.cipd_bin\3.8\bin\Lib\subprocess.py", line 194, in Close
    CloseHandle(self)
OSError: [WinError 6] The handle is invalid

**Comment by jeypevillarubia** [comment]
still got the same error on sycn.log but I got this error on config.log

Updating depot_tools...
Downloading CIPD client for windows-amd64 from https://chrome-infra-packages.appspot.com/client?platform=windows-amd64&version=git_revision:89ada246fcbf10f330011e4991d017332af2365b...
[P21756 00:52:41.488 storage.go:264 W] [fetch 1/3] Transient error: writing to the output instance file: unexpected EOF
WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.

By the way, I am using a company machine, do you think our company security or modification has something to do with the problem?

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional thoughts, questions, or findings related to this topic. Thank you!
